/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface CacheVariantDto {
  createdAt: number;
  lastUsedAt: number;
  modelId: string;
  /** @nullable */
  providerId?: string | null;
  translation: string;
}
