/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface CacheLookupRequest {
  /** @nullable */
  glossary?: string | null;
  /** @nullable */
  modelId?: string | null;
  /**
     * If `None`, returns variants across ALL providers/models (for the UI
     * "show all variants" feature). If set, only returns matching ones.
     * @nullable
     */
  providerId?: string | null;
  source: string;
  /** @nullable */
  systemPrompt?: string | null;
  /** @nullable */
  targetLanguage?: string | null;
}
