/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */

export interface CacheSelectRequest {
  /** @nullable */
  glossary?: string | null;
  modelId: string;
  /** @nullable */
  providerId?: string | null;
  source: string;
  /** @nullable */
  systemPrompt?: string | null;
  /** @nullable */
  targetLanguage?: string | null;
  translation: string;
}
