/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { LlmTarget } from './llmTarget';

export interface LlmCatalogModel {
  languages: string[];
  name: string;
  /**
     * Approximate download size in bytes (for local models only). `None`
     * for cloud providers (no download needed).
     * @minimum 0
     * @nullable
     */
  sizeBytes?: number | null;
  target: LlmTarget;
}
