/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { PipelineStatus } from './pipelineStatus';
import type { PipelineStep } from './pipelineStep';

export interface PipelineProgress {
  /** @minimum 0 */
  currentPage: number;
  /** @minimum 0 */
  currentStepIndex: number;
  /**
     * Wall-clock ms since the whole run started. Used by the UI to show ETA.
     * @minimum 0
     */
  jobElapsedMs?: number;
  jobId: string;
  /** @minimum 0 */
  overallPercent: number;
  status: PipelineStatus;
  step?: null | PipelineStep;
  /**
     * Wall-clock ms the just-completed step took. `0` on the first tick.
     * @minimum 0
     */
  stepElapsedMs?: number;
  /** @minimum 0 */
  totalPages: number;
  /** @minimum 0 */
  totalSteps: number;
}
