/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 */
import type { TextAlign } from './textAlign';
import type { TextShaderEffect } from './textShaderEffect';
import type { TextStrokeStyle } from './textStrokeStyle';

export interface TextStyle {
  /** @items.minimum 0 */
  color: number[];
  effect?: null | TextShaderEffect;
  fontFamilies: string[];
  /** @nullable */
  fontSize?: number | null;
  /**
     * Extra spacing (in px) added between glyphs. `None` (= 0.0) = none.
     * @nullable
     */
  letterSpacing?: number | null;
  /**
     * Line-height multiplier applied to the font-metric line height.
     * `None` (= 1.0) uses the font's natural metrics.
     * @nullable
     */
  lineHeight?: number | null;
  stroke?: null | TextStrokeStyle;
  textAlign?: null | TextAlign;
}
